2015-12-12 23:13:23 DEBUG WorkAppMySQLConnectionManager:128 dhgovindaraj-VirtualBox:5276 Attempting to connect to db at: jdbc:mysql://localhost:3306/
2015-12-12 23:13:23 DEBUG WorkAppMySQLConnectionManager:128 dhgovindaraj-VirtualBox:5276 No available MySQL connections, attempting to create a new one
2015-12-12 23:13:23 DEBUG WorkAppScriptRunnerUtil:128 dhgovindaraj-VirtualBox:5276 
2015-12-12 23:13:23 ERROR WorkAppScriptRunnerUtil:108 dhgovindaraj-VirtualBox:5276  [ Column index out of range. ]  - Stacktrace : java.sql.SQLException: Column index out of range.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:400)
	at com.mysql.jdbc.ResultSetMetaData.getColumnLabel(ResultSetMetaData.java:232)
	at com.workappinc.workappserver.dataaccess.resources.implementation.WorkAppScriptRunnerUtil.runScript(WorkAppScriptRunnerUtil.java:213)
	at com.workappinc.workappserver.dataaccess.resources.implementation.WorkAppScriptRunnerUtil.runScript(WorkAppScriptRunnerUtil.java:105)
	at com.workappinc.workappserver.dataaccess.resources.examples.WorkAppScriptRunnerUtilExample.main(WorkAppScriptRunnerUtilExample.java:39)

2015-12-12 23:13:23 INFO  WorkAppScriptRunnerUtilExample:96 dhgovindaraj-VirtualBox:5276  [ Error executing 'select * from testdb.user  ': Column index out of range. ]  - Stacktrace : java.io.IOException: Error executing 'select * from testdb.user  ': Column index out of range.
	at com.workappinc.workappserver.dataaccess.resources.implementation.WorkAppScriptRunnerUtil.runScript(WorkAppScriptRunnerUtil.java:259)
	at com.workappinc.workappserver.dataaccess.resources.implementation.WorkAppScriptRunnerUtil.runScript(WorkAppScriptRunnerUtil.java:105)
	at com.workappinc.workappserver.dataaccess.resources.examples.WorkAppScriptRunnerUtilExample.main(WorkAppScriptRunnerUtilExample.java:39)
Caused by: java.sql.SQLException: Column index out of range.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:400)
	at com.mysql.jdbc.ResultSetMetaData.getColumnLabel(ResultSetMetaData.java:232)
	at com.workappinc.workappserver.dataaccess.resources.implementation.WorkAppScriptRunnerUtil.runScript(WorkAppScriptRunnerUtil.java:213)
	... 2 more

2015-12-12 23:15:02 DEBUG WorkAppMySQLConnectionManager:128 dhgovindaraj-VirtualBox:5326 Attempting to connect to db at: jdbc:mysql://localhost:3306/
2015-12-12 23:15:02 DEBUG WorkAppMySQLConnectionManager:128 dhgovindaraj-VirtualBox:5326 No available MySQL connections, attempting to create a new one
2015-12-12 23:16:10 DEBUG WorkAppScriptRunnerUtil:128 dhgovindaraj-VirtualBox:5326 
2015-12-12 23:18:35 DEBUG WorkAppMySQLConnectionManager:128 dhgovindaraj-VirtualBox:5486 Attempting to connect to db at: jdbc:mysql://localhost:3306/
2015-12-12 23:18:35 DEBUG WorkAppMySQLConnectionManager:128 dhgovindaraj-VirtualBox:5486 No available MySQL connections, attempting to create a new one
2015-12-12 23:18:35 DEBUG WorkAppScriptRunnerUtil:128 dhgovindaraj-VirtualBox:5486 
2015-12-12 23:18:35 DEBUG WorkAppScriptRunnerUtil:128 dhgovindaraj-VirtualBox:5486 
2015-12-12 23:18:35 DEBUG WorkAppScriptRunnerUtil:128 dhgovindaraj-VirtualBox:5486 
2015-12-12 23:20:20 FATAL WorkAppLoggerTestCase:102 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 ERROR WorkAppLoggerTestCase:108 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 WARN  WorkAppLoggerTestCase:114 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 INFO  WorkAppLoggerTestCase:121 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 DEBUG WorkAppLoggerTestCase:128 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 TRACE WorkAppLoggerTestCase:134 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 INFO  WorkAppLoggerTestCase:96 dhgovindaraj-VirtualBox:5549  [ Test Exception ]  - Stacktrace : java.lang.Exception: Test Exception
	at com.workappinc.workappserver.common.logging.WorkAppLoggerTestCase.Log4jPropertiesConfigOverrideTest(WorkAppLoggerTestCase.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

2015-12-12 23:20:20 INFO  WorkAppLoggerTestCase:89 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 FATAL WorkAppLoggerTestCase:102 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 ERROR WorkAppLoggerTestCase:108 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 WARN  WorkAppLoggerTestCase:114 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 INFO  WorkAppLoggerTestCase:121 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 DEBUG WorkAppLoggerTestCase:128 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 TRACE WorkAppLoggerTestCase:134 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:20:20 INFO  WorkAppLoggerTestCase:96 dhgovindaraj-VirtualBox:5549  [ Test Exception ]  - Stacktrace : java.lang.Exception: Test Exception
	at com.workappinc.workappserver.common.logging.WorkAppLoggerTestCase.doBasicTest(WorkAppLoggerTestCase.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

2015-12-12 23:20:20 INFO  WorkAppLoggerTestCase:89 dhgovindaraj-VirtualBox:5549  [2634b48f-c7ee-418c-8d0a-7c1fb3a1fc99,Test GUID] 
2015-12-12 23:22:14 DEBUG WorkAppMySQLConnectionManager:128 dhgovindaraj-VirtualBox:5608 Attempting to connect to db at: jdbc:mysql://localhost:3306/
2015-12-12 23:22:14 DEBUG WorkAppMySQLConnectionManager:128 dhgovindaraj-VirtualBox:5608 No available MySQL connections, attempting to create a new one
2015-12-12 23:22:14 DEBUG WorkAppScriptRunnerUtil:128 dhgovindaraj-VirtualBox:5608 
2015-12-12 23:22:14 ERROR WorkAppScriptRunnerUtil:108 dhgovindaraj-VirtualBox:5608 Error executing 'create database testdb1 ' (line 1): Can't create database 'testdb1'; database exists
2015-12-12 23:22:14 DEBUG WorkAppScriptRunnerUtil:128 dhgovindaraj-VirtualBox:5608 
2015-12-12 23:22:14 DEBUG WorkAppScriptRunnerUtil:128 dhgovindaraj-VirtualBox:5608 
2015-12-12 23:22:14 ERROR WorkAppScriptRunnerUtil:108 dhgovindaraj-VirtualBox:5608 Error executing 'create table user1 (name text) ' (line 3): Table 'user1' already exists
2015-12-12 23:22:14 DEBUG WorkAppMySQLConnectionManager:128 dhgovindaraj-VirtualBox:5608 Closing all MySQL connections!
